name = input("enter your name:")
surname = input("enter your surname:")
age = input("enter your age:")
password = input("enter your password:")
email = input("enter your email:")
last_name = input("enter your last name:")
user_name = input("enter your user name:")
time_to_work = input("when do you want to work:")
where_to_work = input("where do you want to work:")
minutes_to_work = input("how many minutes you wanna work:")
when_to_start_learning = input("when do you want to start:")
when_to_end_learning = input("when do you want to stop learning:")
do_you_know_coding = input("do you know coding a bit:")
wanna_start_coding = input("start learning:")
learning = input("open link to join goa")
teacher = input("which teacher do you want? data tezelaSvili or others:")
joined_goa = input("text teacher about yourself:")
work_Goa = input("do you like goa?:")
become_chad = input("do you think this was worth it?:")
work_done_work_again = input("your work is done. wanna work more?:")
work_with_same_teacher = input("do you want same teacher?:")

print(name)
print(surname)
print(age)
print(password)
print(email)
print(last_name)
print(user_name)
print(time_to_work)
print(where_to_work)
print(minutes_to_work)
print(when_to_start_learning)
print(when_to_end_learning)
print(do_you_know_coding)
print(wanna_start_coding)
print(learning)
print(teacher)
print(joined_goa)
print(work_Goa)
print(become_chad)
print(work_done_work_again)
print(work_with_same_teacher)
